In [ ]:
#test
x = int(input("Enter 1st number "))
y = int(input("Enter 2nd number "))
z = x+y
print(z)

In [2]:
if(5 > 2):
    print("5 > 2")

5 > 2


In [8]:
x,y,z = 5 ,10, "abc"
print(x + y)
print(y + 10)
print(z + "abc")

15
20
abcabc


In [12]:
x = "fantastic"
def func():
    global x
    x = "awesome"
    print("python is" + x)
    
func()
print("pyhton is" + x)

python isawesome
pyhton isawesome


In [3]:
from numpy import *

arr = array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [1]:
if True:
    print("Hii")
    print("Ravi")

Hii
Ravi


In [17]:
a = int(input("Enter number of rows "))
i = 1;
while i<=a:
    j=1
    while j<=i:
        print("# ",end="")
        j += 1
    print()
    i += 1 


Enter number of rows 5
# 
# # 
# # # 
# # # # 
# # # # # 


In [25]:
for i in range(1,11):
    if i == 2:
        continue
    print(i," ", end = "")

1  3  4  5  6  7  8  9  10  

In [28]:
from array import *
vals = array("i", [1,2,3,4,5])

for e in vals:
    print(e)

1
2
3
4
5


In [ ]:
from array import *
n = int(input("Enter the length of array "))

arr = array('i', [])

for i in range(n):
    x = int(input("Enter the element"))
    arr.append(x)

print(arr)

val = int(input("Enter the element to be search"))

k=0
for e in arr:
    if e == val:
        print(k)
        break
        
    k += 1
    
print(arr.index(val))

In [ ]:
import numpy

arr = array([1,2,3,4,5])
print arr

In [14]:
from numpy import *
arr = array([[1,2,3,4,5],[6,7,8,9]])

for e in arr:
    for f in e:
        print(f, " ",end = "")
    print()

1  2  3  4  5  
6  7  8  9  


In [22]:
string = "ravi"
print(string[::-1])

ivar


In [24]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [29]:
x = 10
y = 10
print(id(x))
print(id(y))

140733441545312
140733441545312


In [30]:
x = int(input("Enter the 1st number "))
y = int(input("Enter the 2nd number "))
z = x + y
print(z)

Enter the 1st number 10
Enter the 2nd number 20
30


In [31]:
print(type(input()))

10
<class 'str'>


In [32]:
x = 10
print(id(10))

140733441545312


In [34]:
x = 10
y = 10
z = 20
print(id(x))
print(id(y))
print(id(z))

140733441545312
140733441545312
140733441545632


In [43]:
x = int(input())
for i in range(0, x, -1):
    print(i)

5


In [50]:
num_list = []
num = int(input())

for i in range(0,num):
    num_list.append(int(input()))
    
print(num_list)
num_list.sort()
print(num_list)
print("min ", num_list[0])
print("max ",num_list[-1])

5
4
7
6
7
4
[4, 7, 6, 7, 4]
[4, 4, 6, 7, 7]
min  4
max  7


In [10]:
from numpy import *
arr = array([1,2,3,4,5, 6.5])
print(arr.dtype)
print(arr)

float64
[1.  2.  3.  4.  5.  6.5]


In [11]:
arr2 = ones(5, int)
print(arr2)

[1 1 1 1 1]


In [18]:
arr1 = array([1,2,3,4,5])
arr2 = arr1.view() #shallow copy
print(arr1, " ", id(arr1))
print(arr2, " ", id(arr2))

arr1[0] = 10
print(arr1, " ", id(arr1))
print(arr2, " ", id(arr2))

arr2 = arr1.copy() #deep copy
arr1[0] = 20
print(arr1, " ", id(arr1))
print(arr2, " ", id(arr2))

[1 2 3 4 5]   2162046077648
[1 2 3 4 5]   2162046077168
[10  2  3  4  5]   2162046077648
[10  2  3  4  5]   2162046077168
[20  2  3  4  5]   2162046077648
[10  2  3  4  5]   2162046312320


In [41]:
arr =array([1,2,3,4,25])
arr1=array([15,16,20,21,5])
arr2 = zeros(len(arr), int)
for i in range(len(arr)):
    arr2[i]=arr[i]+arr1[i]
print(arr2)



[16 18 23 25 30]


In [47]:
arr = array([55,45,52,445,562,14,55,4,45,5,47,7,55,1,4,5],int)

max = 0
for i in arr:
    if i > max:
        max = i
        
print("max ", max)

max  562


In [53]:
# functions
def greet():
    print("Hello",end = " ")
    print("Ravi")
    
greet()

Hello Ravi


In [57]:
def add(x,y):
    return x+y
    
ans = add(int(input()),int(input()))
print(ans)

10
20
30


In [60]:
def add_sub(x,y):
    c = x + y
    d = x - y
    return c,d

result1, result2 = add_sub(int(input()), int(input()))
print(result1, result2)

10
20
30 -10


In [65]:
#variable length (when we don't know the number of args provided)
def sum(*b):
    c = 0
    
    for i in b:
        c += i
    print(c)
    
sum(2,3,4,5,3,2,4,3)


26


In [74]:
#keyword variable length arguments
def person(**data):
#     print("name ", name)
    
    for i,j in data.items():
        print(i,j)
        
person(name='ravi',age=34,mob=23123,city='pune')

name ravi
age 34
mob 23123
city pune


In [82]:
a = 10
def something():
#     global a
    a = 9
    x = globals()['a']
    print(x)
    print(a)

something()
print(a)

10
9
10


In [89]:
num = int(input("Enter the number of inputs "))
lst = []
for i in range(0,num):
    lst.append(int(input("Enter the number")))

def count(lst):
    even = 0
    odd = 0 
    for i in lst:
        if i % 2 == 0:
            even += 1
        else:
            odd += 1
            
    return even, odd

even, odd = count(lst)
print("Even number : {} and odd number : {}".format(even,odd))


Enter the number of inputs 5
Enter the number1
Enter the number2
Enter the number3
Enter the number4
Enter the number5
Even number : 2 and odd number : 3


In [95]:
def fib(n):
    a = 0
    b = 1
    for i in range(2,n):
        c = a+b
        a = b
        b = c
        if c > 100:
            return a
        
ans = fib(100)
print("The last number less than 100 is in fibonacci series is", ans)

The last number less than 100 is in fibonacci series is 89


In [105]:
def fact(n):
    ans = 1
    for i in range(1,n+1):
        ans *= i
    return ans
    
print(fact(5))

120


In [108]:
def fact(n):
    if n == 1:
        return n
    
    return n * fact(n-1)

fact(int(input()))

5


120

In [2]:
# anonyms function (lambda)
# when we have a function of single line expression
f = lambda a : a*a

result = f(5)

print("Square of {} is : ".format(int(input("Enter the number : "))), result)

Enter the number : 10
Square of 10 is :  25


In [15]:
from functools import reduce
nums = [12,4,55,55,6,1,3,25,4,6,1,1,62,26,621,3]

evens = list(filter(lambda a : a%2 == 0,nums))
print(evens)

doubles = list(map(lambda a : a*2,evens))
print(doubles)

add = reduce(lambda a,b : a+b,doubles)
print(add)

[12, 4, 6, 4, 6, 62, 26]
[24, 8, 12, 8, 12, 124, 52]
240


In [20]:
#decoratoes : When we do not want to change the existing func without changing its defination
#wap to divide 2 number ,if num < deno, swap and divide
def div(a,b):
    print(a/b)
    
def smart_div(func):
    
    def inner(a,b):
        if a < b:
            a,b = b,a
        return func(a,b)
    return inner

div = smart_div(div)

div(4,5)

1.25


In [30]:
#class in python
class computer:
    
    def details(self):
        print("Dell, i5, 2TB")
        
com1 = computer()
com1.details()

Dell, i5, 2TB


In [39]:
#__init__ method (constructor)

class computer:
    
    def __init__(self, r, c):
        self.ram = r
        self.cpu = c
        
    def config(self):
        print("Config is : ",self.ram, self.cpu)
        
        
com1 = computer("i5", "15")
com2 = computer("i3", "10")

com1.config()
com2.config()

Config is :  i5 15
Config is :  i3 10


In [48]:
class computer:
    
    def __init__(self):
        self.name = "Ravi"
        self.age = 23
        
        
    def compare(self, c2):
        return self.age == c2.age
    
c1 = computer()
# c1.age = 25
c2 = computer()

# if c1.age == c2.age:
#     print("Same age")
# else:
#     print("Different Age")

if(c1.compare(c2)):
    print("same")
else:
    print("different")


    
        

same


In [2]:
#class variables
class car:
    wheels = 4    #class variable
    
    def __init__(self):
        self.mil = 10     #instance / object variable
        self.company = "BMW"
        
c1 = car()
c2 = car()

# car.wheels = 5

print(c1.mil, c1.company, car.wheels)
print(c2.mil, c2.company, car.wheels)

10 BMW 4
10 BMW 4


In [24]:
# instance method and class method
class student:
    school = "MIT"
    
    def __init__(self, m1, m2, m3):
        self.m1 = m1
        self.m2 = m2
        self.m3 = m3
        
    def avg(self):  #instance method
        return (self.m1 + self.m2 + self.m3) / 3
    
    @classmethod
    def get_school(cls):   #class method
        return cls.school
    
    @staticmethod
    def info():             #static method
        print("This is static method...")
        return "Also static"
        
s1 = student(20,50,60)
s2 = student(55,45,54)

print(s1.avg(), student.get_school())
print(s2.avg(), student.get_school())

print(student.get_school())

x = student.info()
print(x)

43.333333333333336 MIT
51.333333333333336 MIT
MIT
This is static method...
Also static


In [41]:
# class inside a class
class student:
    
    def __init__(self, name, rollno):
        self.name = name
        self.rollno = rollno
#         self.lap = self.laptop("DELL", 8) #creating obj of inner class inside the outer class
        
    def show(self):
        print(self.name, self.rollno)
#         self.lap.show()
        
        
    class laptop:
        
        def __init__(self, brand, ram):
            self.brand = brand
            self.ram = ram
            
        def show(self):
            print(self.brand, self.ram)
            
            
        
s1 = student('ravi', 1, )
s2 = student('vishal', 42)

lap1 = student.laptop("DELL", 8) #creating obj of inner class outside the outer class

s1.show()
s2.show()
lap1.show()

ravi 1
vishal 42
DELL 8


In [57]:
# inheritance
class A:
    def feature1(self):
        print("Feature 1 is working...")
    
    def feature2(self):
        print("Feature 2 is working...")
        
class B:
    
    def feature3(self):
        print("Feature 3 is working...")
        
    def feature4(self):
        print("Feature 4 is working...")
        
        
class C(A,B):
    def feature5(self):
        print("Feature 5 is working...")


b1 = B()
# b1.feature1()
b1.feature4()

c1 = C()
c1.feature5()
c1.feature1()

Feature 4 is working...
Feature 5 is working...
Feature 1 is working...


In [69]:
# constructor in ingeritance and MRO(Method Resolution Order)
class A:
    def __init__(self):
        print("In A init")
        
    def feature1(self):
        print("Feature 1 working")
        
class B:
    def __init__(self):
        print("In B init")
        
    def feature2(self):
        print("Feature 2 is working")
        
class C(A,B):                # MRO i.e left to right
    def __init__(self):
        super().__init__()   # calling constructor of super class A since MRO
        print("In C init")
        
    def feature3(self):
        print("Feature 3 is working")
        
    def newFeature(self):
        super().feature2()  #super can be used to call any function of super class
        
c1 = C()
c1.newFeature()


    

In A init
In C init
Feature 2 is working


In [76]:
#duck typing

class PyCharm:
    
    def execute(self):
        print("Compiling...")
        print("Executing...")

        
class MyEditor:
     def execute(self):
        print("Compiling...")
        print("Executing...")
        print("Spell Check...")
        
class Laptop:
    
    def code(self,ide):
        ide.execute()
        
ide = MyEditor()

l1 = Laptop()
l1.code(ide)
        

Compiling...
Executing...
Spell Check...


In [82]:
# operator overloading
class student:
    
    def __init__(self, m1, m2):
        self.m1 = m1
        self.m2 = m2
        
    def __add__(self, other):  # overloading the inbuilt add method
        r1 = self.m1 + other.m1
        r2 = self.m2 + other.m2
        s = student(r1, r2)
        return s
    
    def __gt__(self, other): # overloading > operator (__gt__()) (greater than)
        r1 = self.m1 + self.m2
        r2 = other.m1 + other.m2
        return r1 > r2
    
s1 = student(45,50)
s2 = student(50,50)

s3 = s1 + s2  

print(s3.m1, s3.m2)

if s1 > s2:
    print("s1 got higher marks")
else:
    print("s2 get higher marks")
    



95 100
s2 get higher marks
